### ISSUE TITLE
failed to configure

### ISSUE THREAD

**Issue by dmaglio** [rakanalh/pocket-cli#11]
after i have installed pocket-cli and i try to `pocket-cli configure` 

```
Please provide your consumer key: 
Please provide your consumer key: 5XXXX-c5XXXXXXXXXXXXXXXXXXXXXXX
Please provide your preferred sort field
    Available options are [id, reading_time]
    default: [reading_time]: reading_time
Please specify your reading speed in words per minute
    You can use this URL to estimate your reading time
    http://www.readingsoft.com/
    default: [180]: 1000
Traceback (most recent call last):
  File "/usr/bin/pocket-cli", line 11, in <module>
    load_entry_point('pocket-cli==0.1.4', 'console_scripts', 'pocket-cli')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pocket_cli/cli.py", line 51, in configure
    request_token = pocket_app.get_request_token(consumer_key)
  File "/usr/lib/python2.7/site-packages/pocket_cli/app.py", line 48, in get_request_token
    consumer_key, self.REDIRECT_URL
TypeError: get_request_token() takes exactly 2 arguments (3 given)
```

**Comment by rakanalh** [comment]
Oh yes... that must have been a regression when updating pocket-api. I'll get a fix tonight for this.

Thank you for reporting the issue.
