### ISSUE TITLE
KeyError: ‘word_count’

### ISSUE THREAD

**Issue by kseistrup** [rakanalh/pocket-cli#5]
When trying to fetch articles for the first time after configuring:

``` pytb
$ pocket-cli fetch
Loading articles \Traceback (most recent call last):
  File "/usr/bin/pocket-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pocket_cli/cli.py", line 177, in fetch
    pocket_app.fetch_articles(True)
  File "/usr/lib/python3.5/site-packages/pocket_cli/app.py", line 129, in fetch_articles
    articles_index.extend(self._get_articles_index(articles))
  File "/usr/lib/python3.5/site-packages/pocket_cli/app.py", line 162, in _get_articles_index
    word_count = int(article['word_count'])
KeyError: 'word_count'
```

Pocket-CLI doesn't seem to have a `--version` option, but it's the latest from PyPI.

**Comment by rakanalh** [comment]
Thank you for the report. 
I find this quite strange given that pocket should always provide a word count. Could you please add:

```
print(article['resolved_url'])
print(article['given_url'])
```

On line 161... i am interested to see that specific URL and why it doesn't contain that specific key. Otherwise, the issue should be easy to fix but this is out of curiosity.

Thanks

**Comment by kseistrup** [comment]
The first offending article is

``` json
{
  "favorite": "0",
  "given_title": "Våbenindustrien fik mange milliardkontrakter i 2015 · D′",
  "given_url": "https://d-prime.dk/2015/12/27/milliardkontrakter-til-v%C3%A5benindustrien/",
  "item_id": "1147074358",
  "resolved_id": "0",
  "sort_id": 15,
  "status": "0",
  "time_added": "1451407562",
  "time_favorited": "0",
  "time_read": "0",
  "time_updated": "1451407562"
}
```

There was no `resolved_url` field.

**Comment by kseistrup** [comment]
Additional bug, that should probably be filed in a separate issue: When Pocket-CLI exits with an exception, it leaves the terminal b0rked: there is no longer any cursor. Running `reset` will fix the problem.  Does Pocket-CLI tamper with the terminal's properties?

**Comment by rakanalh** [comment]
Ah so word_count isn't added to the response element. Should be an easy fix.

I think the terminal issue is probably related to the `progress` package after fetching content and the call to it's finish() method.
